-- Seed countries table with common countries
-- This script populates the countries table with ISO 3166-1 alpha-2 country codes

INSERT INTO public.countries (code, name, iso3, region) VALUES
('GB', 'United Kingdom', 'GBR', 'Europe'),
('US', 'United States', 'USA', 'North America'),
('CA', 'Canada', 'CAN', 'North America'),
('AU', 'Australia', 'AUS', 'Oceania'),
('NZ', 'New Zealand', 'NZL', 'Oceania'),
('FR', 'France', 'FRA', 'Europe'),
('DE', 'Germany', 'DEU', 'Europe'),
('IT', 'Italy', 'ITA', 'Europe'),
('ES', 'Spain', 'ESP', 'Europe'),
('PT', 'Portugal', 'PRT', 'Europe'),
('NL', 'Netherlands', 'NLD', 'Europe'),
('BE', 'Belgium', 'BEL', 'Europe'),
('CH', 'Switzerland', 'CHE', 'Europe'),
('AT', 'Austria', 'AUT', 'Europe'),
('IE', 'Ireland', 'IRL', 'Europe'),
('DK', 'Denmark', 'DNK', 'Europe'),
('SE', 'Sweden', 'SWE', 'Europe'),
('NO', 'Norway', 'NOR', 'Europe'),
('FI', 'Finland', 'FIN', 'Europe'),
('PL', 'Poland', 'POL', 'Europe'),
('CZ', 'Czech Republic', 'CZE', 'Europe'),
('GR', 'Greece', 'GRC', 'Europe'),
('TR', 'Turkey', 'TUR', 'Europe'),
('RU', 'Russia', 'RUS', 'Europe'),
('JP', 'Japan', 'JPN', 'Asia'),
('CN', 'China', 'CHN', 'Asia'),
('KR', 'South Korea', 'KOR', 'Asia'),
('IN', 'India', 'IND', 'Asia'),
('SG', 'Singapore', 'SGP', 'Asia'),
('MY', 'Malaysia', 'MYS', 'Asia'),
('TH', 'Thailand', 'THA', 'Asia'),
('ID', 'Indonesia', 'IDN', 'Asia'),
('PH', 'Philippines', 'PHL', 'Asia'),
('VN', 'Vietnam', 'VNM', 'Asia'),
('AE', 'United Arab Emirates', 'ARE', 'Asia'),
('SA', 'Saudi Arabia', 'SAU', 'Asia'),
('IL', 'Israel', 'ISR', 'Asia'),
('ZA', 'South Africa', 'ZAF', 'Africa'),
('EG', 'Egypt', 'EGY', 'Africa'),
('KE', 'Kenya', 'KEN', 'Africa'),
('MA', 'Morocco', 'MAR', 'Africa'),
('BR', 'Brazil', 'BRA', 'South America'),
('AR', 'Argentina', 'ARG', 'South America'),
('CL', 'Chile', 'CHL', 'South America'),
('CO', 'Colombia', 'COL', 'South America'),
('MX', 'Mexico', 'MEX', 'North America'),
('CR', 'Costa Rica', 'CRI', 'North America'),
('JM', 'Jamaica', 'JAM', 'North America'),
('BS', 'Bahamas', 'BHS', 'North America'),
('IS', 'Iceland', 'ISL', 'Europe'),
('LU', 'Luxembourg', 'LUX', 'Europe'),
('MT', 'Malta', 'MLT', 'Europe'),
('CY', 'Cyprus', 'CYP', 'Europe')
ON CONFLICT (code) DO NOTHING;

-- Verify the insert
SELECT COUNT(*) as total_countries FROM public.countries;

