-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accommodation_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  allocation_id uuid NOT NULL,
  booking_id uuid,
  quote_id uuid,
  rooms_allocated integer NOT NULL CHECK (rooms_allocated > 0),
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  status character varying DEFAULT 'provisional'::character varying CHECK (status::text = ANY (ARRAY['provisional'::character varying, 'confirmed'::character varying, 'released'::character varying]::text[])),
  expiry_datetime timestamp with time zone,
  allocated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  confirmed_at timestamp with time zone,
  released_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accommodation_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT accommodation_allocations_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.contract_room_allocations(id),
  CONSTRAINT accommodation_allocations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT accommodation_allocations_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.accommodation_charges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid,
  allocation_id uuid,
  charge_type character varying NOT NULL,
  charge_name character varying NOT NULL,
  calculation_method character varying NOT NULL,
  amount numeric,
  percentage numeric,
  currency character varying DEFAULT 'GBP'::character varying,
  is_included boolean DEFAULT false,
  is_mandatory boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accommodation_charges_pkey PRIMARY KEY (id),
  CONSTRAINT accommodation_charges_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.accommodation_contracts(id),
  CONSTRAINT accommodation_charges_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.contract_room_allocations(id),
  CONSTRAINT accommodation_charges_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.accommodation_contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  property_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  event_id uuid,
  contract_reference character varying,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  minimum_stay_nights integer,
  release_date date,
  rooming_list_due_date date,
  payment_terms text,
  deposit_percentage numeric,
  deposit_due_date date,
  final_payment_due_date date,
  cancellation_policy text,
  supplier_commission_percentage numeric,
  supplier_commission_amount numeric,
  special_terms text,
  contract_document_url character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'released'::character varying, 'completed'::character varying]::text[])),
  notes text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT accommodation_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT accommodation_contracts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT accommodation_contracts_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.accommodation_properties(id),
  CONSTRAINT accommodation_contracts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT accommodation_contracts_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.accommodation_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  allocation_id uuid NOT NULL,
  occupancy_type character varying NOT NULL,
  guests_count integer NOT NULL,
  cost_per_night numeric NOT NULL CHECK (cost_per_night >= 0::numeric),
  currency character varying DEFAULT 'GBP'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accommodation_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT accommodation_pricing_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.contract_room_allocations(id),
  CONSTRAINT accommodation_pricing_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.accommodation_properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  supplier_id uuid,
  name character varying NOT NULL,
  property_type character varying NOT NULL,
  star_rating numeric,
  city character varying NOT NULL,
  country_code character varying,
  address text,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  phone character varying,
  email character varying,
  website character varying,
  description text,
  amenities jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  external_property_id character varying,
  api_sync_enabled boolean DEFAULT false,
  last_synced_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT accommodation_properties_pkey PRIMARY KEY (id),
  CONSTRAINT accommodation_properties_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT accommodation_properties_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT accommodation_properties_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code)
);
CREATE TABLE public.board_basis_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  allocation_id uuid NOT NULL,
  board_type character varying NOT NULL,
  is_included boolean DEFAULT true,
  price_per_person_per_night numeric,
  currency character varying DEFAULT 'GBP'::character varying,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT board_basis_options_pkey PRIMARY KEY (id),
  CONSTRAINT board_basis_options_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.contract_room_allocations(id),
  CONSTRAINT board_basis_options_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_accommodation_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  package_component_id uuid NOT NULL,
  allocation_id uuid NOT NULL,
  room_type_name character varying NOT NULL,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  nights integer NOT NULL,
  quantity integer NOT NULL,
  cost_per_unit numeric NOT NULL,
  selling_price_per_unit numeric NOT NULL,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  component_details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_accommodation_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_accommodation_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_accommodation_components_package_component_id_fkey FOREIGN KEY (package_component_id) REFERENCES public.package_components(id),
  CONSTRAINT booking_accommodation_components_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.accommodation_allocations(id),
  CONSTRAINT booking_accommodation_components_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_communications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  quote_id uuid,
  communication_type character varying NOT NULL,
  direction character varying,
  subject character varying,
  message text,
  communicated_by uuid,
  communicated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_communications_pkey PRIMARY KEY (id),
  CONSTRAINT booking_communications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_communications_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.booking_corporate_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  company_name character varying NOT NULL,
  custom_branding boolean DEFAULT false,
  branding_details jsonb DEFAULT '{}'::jsonb,
  welcome_packs boolean DEFAULT false,
  welcome_pack_quantity integer,
  welcome_pack_cost numeric,
  custom_merchandise boolean DEFAULT false,
  merchandise_details jsonb DEFAULT '{}'::jsonb,
  dedicated_account_manager boolean DEFAULT false,
  account_manager_name character varying,
  custom_invoice_terms text,
  payment_terms character varying,
  total_customization_cost numeric,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_corporate_options_pkey PRIMARY KEY (id),
  CONSTRAINT booking_corporate_options_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  document_type character varying NOT NULL,
  document_name character varying NOT NULL,
  file_url character varying NOT NULL,
  file_size integer,
  mime_type character varying,
  generated_at timestamp with time zone,
  sent_to_customer boolean DEFAULT false,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_documents_pkey PRIMARY KEY (id),
  CONSTRAINT booking_documents_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_extra_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  package_component_id uuid NOT NULL,
  extra_id uuid NOT NULL,
  extra_name character varying NOT NULL,
  quantity integer NOT NULL,
  cost_per_unit numeric NOT NULL,
  selling_price_per_unit numeric NOT NULL,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  component_details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_extra_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_extra_components_package_component_id_fkey FOREIGN KEY (package_component_id) REFERENCES public.package_components(id),
  CONSTRAINT booking_extra_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_extra_components_extra_id_fkey FOREIGN KEY (extra_id) REFERENCES public.product_extras(id),
  CONSTRAINT booking_extra_components_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_extra_nights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  allocation_id uuid NOT NULL,
  extra_nights_before integer DEFAULT 0,
  extra_nights_after integer DEFAULT 0,
  cost_per_night numeric NOT NULL,
  total_cost numeric NOT NULL,
  selling_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_extra_nights_pkey PRIMARY KEY (id),
  CONSTRAINT booking_extra_nights_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_extra_nights_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.contract_room_allocations(id),
  CONSTRAINT booking_extra_nights_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  fee_type character varying NOT NULL,
  fee_name character varying NOT NULL,
  calculation_method character varying NOT NULL,
  amount numeric,
  percentage numeric,
  is_mandatory boolean DEFAULT true,
  is_refundable boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_fees_pkey PRIMARY KEY (id),
  CONSTRAINT booking_fees_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_flight_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  package_component_id uuid NOT NULL,
  flight_id uuid,
  flight_details character varying,
  quantity integer NOT NULL,
  cost_per_passenger numeric NOT NULL,
  selling_price_per_passenger numeric NOT NULL,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  component_details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_flight_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_flight_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_flight_components_package_component_id_fkey FOREIGN KEY (package_component_id) REFERENCES public.package_components(id),
  CONSTRAINT booking_flight_components_flight_id_fkey FOREIGN KEY (flight_id) REFERENCES public.flights(id),
  CONSTRAINT booking_flight_components_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_guests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  guest_type character varying NOT NULL CHECK (guest_type::text = ANY (ARRAY['adult'::character varying, 'child'::character varying, 'infant'::character varying]::text[])),
  is_lead_guest boolean DEFAULT false,
  title character varying,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  date_of_birth date,
  age_at_travel integer,
  email character varying,
  phone character varying,
  passport_number character varying,
  passport_expiry date,
  passport_issue_country character varying,
  nationality character varying,
  dietary_requirements text,
  special_requests text,
  medical_conditions text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_guests_pkey PRIMARY KEY (id),
  CONSTRAINT booking_guests_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_guests_passport_issue_country_fkey FOREIGN KEY (passport_issue_country) REFERENCES public.countries(code),
  CONSTRAINT booking_guests_nationality_fkey FOREIGN KEY (nationality) REFERENCES public.countries(code)
);
CREATE TABLE public.booking_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  payment_type character varying NOT NULL CHECK (payment_type::text = ANY (ARRAY['deposit'::character varying, 'balance'::character varying, 'refund'::character varying, 'amendment'::character varying]::text[])),
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  currency character varying DEFAULT 'GBP'::character varying,
  payment_method character varying,
  payment_reference character varying,
  transaction_id character varying,
  payment_date date NOT NULL,
  status character varying DEFAULT 'completed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  notes text,
  processed_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_payments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_payments_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  from_status character varying,
  to_status character varying NOT NULL,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  notes text,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT booking_status_history_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_ticket_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  package_component_id uuid NOT NULL,
  ticket_allocation_id uuid NOT NULL,
  ticket_name character varying NOT NULL,
  category_name character varying,
  quantity integer NOT NULL,
  cost_per_ticket numeric NOT NULL,
  selling_price_per_ticket numeric NOT NULL,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  component_details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_ticket_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_ticket_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_ticket_components_package_component_id_fkey FOREIGN KEY (package_component_id) REFERENCES public.package_components(id),
  CONSTRAINT booking_ticket_components_ticket_allocation_id_fkey FOREIGN KEY (ticket_allocation_id) REFERENCES public.ticket_allocations(id),
  CONSTRAINT booking_ticket_components_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.booking_transfer_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  package_component_id uuid NOT NULL,
  route_name character varying NOT NULL,
  transfer_type character varying NOT NULL,
  transfer_date date,
  quantity integer NOT NULL,
  cost_per_unit numeric NOT NULL,
  selling_price_per_unit numeric NOT NULL,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  component_details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT booking_transfer_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_transfer_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_transfer_components_package_component_id_fkey FOREIGN KEY (package_component_id) REFERENCES public.package_components(id),
  CONSTRAINT booking_transfer_components_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  booking_reference character varying NOT NULL UNIQUE,
  quote_id uuid,
  package_id uuid NOT NULL,
  customer_name character varying NOT NULL,
  customer_email character varying NOT NULL,
  customer_phone character varying,
  customer_address text,
  number_of_guests integer NOT NULL CHECK (number_of_guests > 0),
  occupancy_type character varying,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  gross_margin numeric DEFAULT (total_price - total_cost),
  margin_percentage numeric DEFAULT 
CASE
    WHEN (total_price > (0)::numeric) THEN (((total_price - total_cost) / total_price) * (100)::numeric)
    ELSE (0)::numeric
END,
  booking_fee numeric DEFAULT 0,
  service_fee numeric DEFAULT 0,
  credit_card_fee numeric DEFAULT 0,
  credit_card_fee_percentage numeric,
  is_corporate boolean DEFAULT false,
  corporate_company_name character varying,
  corporate_branding_options jsonb DEFAULT '{}'::jsonb,
  invoice_terms text,
  payment_terms character varying,
  status character varying DEFAULT 'provisional'::character varying CHECK (status::text = ANY (ARRAY['provisional'::character varying, 'confirmed'::character varying, 'cancelled'::character varying, 'completed'::character varying]::text[])),
  booking_date date DEFAULT CURRENT_DATE,
  travel_date date,
  special_requests text,
  internal_notes text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT bookings_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT bookings_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT bookings_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.contract_room_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  room_type_id uuid NOT NULL,
  total_rooms integer NOT NULL CHECK (total_rooms > 0),
  version integer NOT NULL DEFAULT 1,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contract_room_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT contract_room_allocations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.accommodation_contracts(id),
  CONSTRAINT contract_room_allocations_room_type_id_fkey FOREIGN KEY (room_type_id) REFERENCES public.room_types(id)
);
CREATE TABLE public.countries (
  code character varying NOT NULL,
  name character varying NOT NULL,
  iso3 character varying,
  region character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT countries_pkey PRIMARY KEY (code)
);
CREATE TABLE public.currencies (
  code character varying NOT NULL,
  name character varying NOT NULL,
  symbol character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT currencies_pkey PRIMARY KEY (code)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  sport_id uuid NOT NULL,
  tournament_id uuid,
  venue_id uuid NOT NULL,
  home_team_id uuid,
  visiting_team_id uuid,
  start_date date NOT NULL,
  end_date date NOT NULL,
  main_event_date date,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'cancelled'::character varying, 'completed'::character varying, 'sold_out'::character varying]::text[])),
  is_featured boolean DEFAULT false,
  image_url character varying,
  images jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT events_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES public.sports(id),
  CONSTRAINT events_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT events_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id),
  CONSTRAINT events_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT events_visiting_team_id_fkey FOREIGN KEY (visiting_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  from_currency character varying NOT NULL,
  to_currency character varying NOT NULL,
  rate numeric NOT NULL,
  effective_date date NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id),
  CONSTRAINT exchange_rates_from_currency_fkey FOREIGN KEY (from_currency) REFERENCES public.currencies(code),
  CONSTRAINT exchange_rates_to_currency_fkey FOREIGN KEY (to_currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.extra_nights_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  room_type_id uuid NOT NULL,
  date_from date NOT NULL,
  date_to date NOT NULL,
  occupancy_type character varying NOT NULL,
  cost_per_night numeric,
  currency character varying DEFAULT 'GBP'::character varying,
  availability_status character varying DEFAULT 'on_request'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT extra_nights_rates_pkey PRIMARY KEY (id),
  CONSTRAINT extra_nights_rates_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.accommodation_contracts(id),
  CONSTRAINT extra_nights_rates_room_type_id_fkey FOREIGN KEY (room_type_id) REFERENCES public.room_types(id),
  CONSTRAINT extra_nights_rates_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.flights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  source character varying NOT NULL CHECK (source::text = ANY (ARRAY['api'::character varying, 'manual'::character varying]::text[])),
  booking_reference character varying,
  airline_code character varying,
  airline_name character varying,
  flight_number character varying,
  departure_airport character varying,
  arrival_airport character varying,
  departure_datetime timestamp with time zone,
  arrival_datetime timestamp with time zone,
  cabin_class character varying,
  booking_class character varying,
  baggage_allowance text,
  cost_per_passenger numeric NOT NULL CHECK (cost_per_passenger >= 0::numeric),
  currency character varying DEFAULT 'GBP'::character varying,
  supplier_id uuid,
  status character varying DEFAULT 'quoted'::character varying CHECK (status::text = ANY (ARRAY['quoted'::character varying, 'booked'::character varying, 'ticketed'::character varying, 'cancelled'::character varying]::text[])),
  tickets_issued_date date,
  ticket_numbers jsonb DEFAULT '[]'::jsonb,
  fare_rules text,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT flights_pkey PRIMARY KEY (id),
  CONSTRAINT flights_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT flights_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code),
  CONSTRAINT flights_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.organization_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  email character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'sales_manager'::character varying, 'sales_agent'::character varying, 'operations_manager'::character varying, 'finance_manager'::character varying, 'member'::character varying]::text[])),
  invited_by uuid NOT NULL,
  token uuid NOT NULL DEFAULT gen_random_uuid(),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'expired'::character varying, 'revoked'::character varying]::text[])),
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT organization_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT organization_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.tenants(id),
  CONSTRAINT organization_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying, 'admin'::character varying, 'sales_manager'::character varying, 'sales_agent'::character varying, 'operations_manager'::character varying, 'finance_manager'::character varying, 'member'::character varying]::text[])),
  invited_by uuid,
  joined_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.tenants(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.package_accommodation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL UNIQUE,
  contract_id uuid NOT NULL,
  allocation_id uuid NOT NULL,
  room_type_id uuid NOT NULL,
  board_basis_id uuid,
  check_in_date date NOT NULL,
  check_out_date date NOT NULL,
  nights integer NOT NULL,
  default_occupancy character varying DEFAULT 'double'::character varying,
  allow_extra_nights boolean DEFAULT true,
  extra_nights_before integer DEFAULT 0,
  extra_nights_after integer DEFAULT 0,
  base_cost_single numeric,
  base_cost_double numeric,
  base_cost_triple numeric,
  base_cost_extra_person numeric,
  currency character varying DEFAULT 'GBP'::character varying,
  markup_percentage numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_accommodation_pkey PRIMARY KEY (id),
  CONSTRAINT package_accommodation_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.package_components(id),
  CONSTRAINT package_accommodation_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.accommodation_contracts(id),
  CONSTRAINT package_accommodation_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.contract_room_allocations(id),
  CONSTRAINT package_accommodation_room_type_id_fkey FOREIGN KEY (room_type_id) REFERENCES public.room_types(id),
  CONSTRAINT package_accommodation_board_basis_id_fkey FOREIGN KEY (board_basis_id) REFERENCES public.board_basis_options(id),
  CONSTRAINT package_accommodation_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.package_airport_transfers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL UNIQUE,
  route_id uuid NOT NULL,
  pricing_id uuid NOT NULL,
  vehicle_type_id uuid NOT NULL,
  direction character varying NOT NULL,
  departure_time time without time zone,
  return_time time without time zone,
  pricing_type character varying NOT NULL,
  estimated_cost numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  markup_percentage numeric NOT NULL DEFAULT 0,
  meet_and_greet boolean DEFAULT false,
  meet_and_greet_cost numeric,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_airport_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT package_airport_transfers_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.package_components(id),
  CONSTRAINT package_airport_transfers_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transfer_routes(id),
  CONSTRAINT package_airport_transfers_pricing_id_fkey FOREIGN KEY (pricing_id) REFERENCES public.transfer_pricing(id),
  CONSTRAINT package_airport_transfers_vehicle_type_id_fkey FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_types(id),
  CONSTRAINT package_airport_transfers_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.package_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tour_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT package_categories_pkey PRIMARY KEY (id),
  CONSTRAINT package_categories_tour_id_fkey FOREIGN KEY (tour_id) REFERENCES public.tours(id)
);
CREATE TABLE public.package_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  component_type character varying NOT NULL CHECK (component_type::text = ANY (ARRAY['accommodation'::character varying, 'ticket'::character varying, 'venue_transfer'::character varying, 'airport_transfer'::character varying, 'flight'::character varying, 'extra'::character varying]::text[])),
  component_name character varying NOT NULL,
  is_mandatory boolean DEFAULT true,
  is_included_in_base_price boolean DEFAULT true,
  valid_from date,
  valid_to date,
  sort_order integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT package_components_pkey PRIMARY KEY (id),
  CONSTRAINT package_components_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.package_extras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL UNIQUE,
  extra_id uuid NOT NULL,
  quantity_included integer DEFAULT 1,
  cost_per_unit numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  markup_percentage numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_extras_pkey PRIMARY KEY (id),
  CONSTRAINT package_extras_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.package_components(id),
  CONSTRAINT package_extras_extra_id_fkey FOREIGN KEY (extra_id) REFERENCES public.product_extras(id),
  CONSTRAINT package_extras_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.package_flights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL UNIQUE,
  outbound_flight_id uuid,
  return_flight_id uuid,
  flight_type character varying NOT NULL,
  departure_airport character varying,
  arrival_airport character varying,
  outbound_date date,
  return_date date,
  cabin_class character varying,
  cost_per_passenger numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  markup_percentage numeric NOT NULL DEFAULT 0,
  booking_method character varying DEFAULT 'api'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_flights_pkey PRIMARY KEY (id),
  CONSTRAINT package_flights_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.package_components(id),
  CONSTRAINT package_flights_outbound_flight_id_fkey FOREIGN KEY (outbound_flight_id) REFERENCES public.flights(id),
  CONSTRAINT package_flights_return_flight_id_fkey FOREIGN KEY (return_flight_id) REFERENCES public.flights(id),
  CONSTRAINT package_flights_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.package_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  pricing_name character varying,
  occupancy_type character varying NOT NULL,
  number_of_guests integer NOT NULL CHECK (number_of_guests > 0),
  calculated_cost numeric NOT NULL,
  calculated_price numeric NOT NULL,
  manual_override_price numeric,
  final_price numeric DEFAULT COALESCE(manual_override_price, calculated_price),
  currency character varying DEFAULT 'GBP'::character varying,
  effective_from date,
  effective_to date,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT package_pricing_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT package_pricing_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.package_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL UNIQUE,
  ticket_id uuid NOT NULL,
  inventory_id uuid,
  quantity_per_guest integer DEFAULT 1,
  cost_per_ticket numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  markup_percentage numeric NOT NULL DEFAULT 0,
  inventory_handling character varying DEFAULT 'contracted'::character varying,
  auto_allocate boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT package_tickets_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.package_components(id),
  CONSTRAINT package_tickets_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT package_tickets_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.ticket_inventory(id),
  CONSTRAINT package_tickets_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.package_venue_transfers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL UNIQUE,
  route_id uuid NOT NULL,
  pricing_id uuid NOT NULL,
  vehicle_type_id uuid NOT NULL,
  transfer_dates jsonb DEFAULT '[]'::jsonb,
  departure_time time without time zone,
  return_time time without time zone,
  pricing_type character varying NOT NULL,
  estimated_cost numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  markup_percentage numeric NOT NULL DEFAULT 0,
  is_round_trip boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT package_venue_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT package_venue_transfers_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transfer_routes(id),
  CONSTRAINT package_venue_transfers_pricing_id_fkey FOREIGN KEY (pricing_id) REFERENCES public.transfer_pricing(id),
  CONSTRAINT package_venue_transfers_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.package_components(id),
  CONSTRAINT package_venue_transfers_vehicle_type_id_fkey FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_types(id),
  CONSTRAINT package_venue_transfers_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tour_id uuid NOT NULL,
  category_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  package_code character varying,
  description text,
  highlights text,
  duration_nights integer,
  max_guests integer CHECK (max_guests IS NULL OR max_guests > 0),
  status character varying DEFAULT 'active'::character varying,
  featured boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  images jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_tour_id_fkey FOREIGN KEY (tour_id) REFERENCES public.tours(id),
  CONSTRAINT packages_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.package_categories(id)
);
CREATE TABLE public.product_extras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  event_id uuid,
  name character varying NOT NULL,
  code character varying,
  category character varying,
  description text,
  inventory_type character varying DEFAULT 'unlimited'::character varying,
  total_quantity integer,
  cost_price numeric NOT NULL CHECK (cost_price >= 0::numeric),
  currency character varying DEFAULT 'GBP'::character varying,
  supplier_id uuid,
  requires_details boolean DEFAULT false,
  required_fields jsonb DEFAULT '[]'::jsonb,
  max_per_booking integer,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT product_extras_pkey PRIMARY KEY (id),
  CONSTRAINT product_extras_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT product_extras_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT product_extras_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code),
  CONSTRAINT product_extras_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  quote_number character varying NOT NULL UNIQUE,
  package_id uuid NOT NULL,
  customer_name character varying,
  customer_email character varying,
  customer_phone character varying,
  number_of_guests integer NOT NULL CHECK (number_of_guests > 0),
  occupancy_type character varying,
  special_requests text,
  total_cost numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'GBP'::character varying,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'accepted'::character varying, 'declined'::character varying, 'expired'::character varying]::text[])),
  valid_until date,
  notes text,
  created_by uuid,
  updated_by uuid,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT quotes_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT quotes_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.room_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL,
  name character varying NOT NULL,
  code character varying,
  bed_configuration character varying,
  max_occupancy integer NOT NULL,
  standard_occupancy integer NOT NULL DEFAULT 2,
  size_sqm numeric,
  description text,
  amenities jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT room_types_pkey PRIMARY KEY (id),
  CONSTRAINT room_types_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.accommodation_properties(id)
);
CREATE TABLE public.sports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  slug character varying NOT NULL UNIQUE,
  icon_url character varying,
  image_url character varying,
  description text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT sports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.supplier_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  name character varying NOT NULL,
  position character varying,
  email character varying,
  phone character varying,
  is_primary boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT supplier_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_contacts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  supplier_type character varying NOT NULL,
  contact_name character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  country character varying,
  payment_terms text,
  payment_days integer,
  default_currency character varying,
  api_enabled boolean DEFAULT false,
  api_endpoint character varying,
  api_credentials jsonb DEFAULT '{}'::jsonb,
  api_type character varying,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT suppliers_default_currency_fkey FOREIGN KEY (default_currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  sport_id uuid NOT NULL,
  country_code character varying,
  logo_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT teams_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES public.sports(id),
  CONSTRAINT teams_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  default_currency character varying DEFAULT 'GBP'::character varying,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  logo_url character varying,
  domain character varying,
  subscription_plan character varying DEFAULT 'free'::character varying,
  subscription_status character varying DEFAULT 'active'::character varying,
  max_users integer DEFAULT 10,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ticket_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_id uuid NOT NULL,
  booking_id uuid,
  quote_id uuid,
  quantity_allocated integer NOT NULL CHECK (quantity_allocated > 0),
  status character varying DEFAULT 'provisional'::character varying CHECK (status::text = ANY (ARRAY['provisional'::character varying, 'confirmed'::character varying, 'released'::character varying]::text[])),
  expiry_datetime timestamp with time zone,
  allocated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  confirmed_at timestamp with time zone,
  released_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ticket_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_allocations_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.ticket_inventory(id),
  CONSTRAINT ticket_allocations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT ticket_allocations_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.ticket_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT ticket_categories_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.ticket_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  ticket_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  inventory_type character varying NOT NULL DEFAULT 'contracted'::character varying CHECK (inventory_type::text = ANY (ARRAY['contracted'::character varying, 'free_sell'::character varying, 'buy_to_order'::character varying]::text[])),
  total_quantity integer,
  version integer NOT NULL DEFAULT 1,
  cost_per_ticket numeric NOT NULL CHECK (cost_per_ticket >= 0::numeric),
  currency character varying DEFAULT 'GBP'::character varying,
  supplier_commission_percentage numeric,
  supplier_commission_amount numeric,
  delivery_method character varying,
  lead_time_days integer,
  available_from date,
  available_until date,
  notes text,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT ticket_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_inventory_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id),
  CONSTRAINT ticket_inventory_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT ticket_inventory_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT ticket_inventory_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  event_id uuid NOT NULL,
  category_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  valid_dates jsonb DEFAULT '[]'::jsonb,
  includes text,
  restrictions text,
  external_ticket_id character varying,
  api_sync_enabled boolean DEFAULT false,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tickets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT tickets_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ticket_categories(id)
);
CREATE TABLE public.tour_operations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tour_id uuid NOT NULL,
  departure_date date NOT NULL,
  total_guests integer DEFAULT 0,
  total_bookings integer DEFAULT 0,
  tour_manager_id uuid,
  tour_manager_cost numeric,
  on_site_reps_count integer DEFAULT 0,
  on_site_rep_cost_per_day numeric,
  total_staff_cost numeric,
  rooming_list_completed boolean DEFAULT false,
  rooming_list_sent_date date,
  flight_manifest_completed boolean DEFAULT false,
  transfer_manifest_completed boolean DEFAULT false,
  supplier_confirmations_complete boolean DEFAULT false,
  status character varying DEFAULT 'planning'::character varying,
  notes text,
  staff_notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tour_operations_pkey PRIMARY KEY (id),
  CONSTRAINT tour_operations_tour_id_fkey FOREIGN KEY (tour_id) REFERENCES public.tours(id)
);
CREATE TABLE public.tour_staff_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tour_operation_id uuid NOT NULL,
  staff_type character varying NOT NULL,
  staff_name character varying,
  staff_role character varying,
  start_date date NOT NULL,
  end_date date NOT NULL,
  days_count integer,
  cost_per_day numeric,
  total_cost numeric,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tour_staff_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT tour_staff_allocations_tour_operation_id_fkey FOREIGN KEY (tour_operation_id) REFERENCES public.tour_operations(id)
);
CREATE TABLE public.tournaments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  sport_id uuid NOT NULL,
  season character varying,
  slug character varying NOT NULL,
  description text,
  image_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT tournaments_pkey PRIMARY KEY (id),
  CONSTRAINT tournaments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tournaments_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES public.sports(id)
);
CREATE TABLE public.tours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  event_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  highlights text,
  inclusions text,
  exclusions text,
  terms_and_conditions text,
  booking_open_date date,
  booking_close_date date,
  status character varying DEFAULT 'active'::character varying,
  featured boolean DEFAULT false,
  images jsonb DEFAULT '[]'::jsonb,
  seo_title character varying,
  seo_description text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT tours_pkey PRIMARY KEY (id),
  CONSTRAINT tours_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tours_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.transfer_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL,
  vehicle_type_id uuid NOT NULL,
  pricing_type character varying NOT NULL CHECK (pricing_type::text = ANY (ARRAY['per_seat'::character varying, 'per_vehicle'::character varying]::text[])),
  estimated_cost numeric NOT NULL CHECK (estimated_cost >= 0::numeric),
  currency character varying DEFAULT 'GBP'::character varying,
  max_bookable_quantity integer,
  minimum_passengers integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transfer_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_pricing_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transfer_routes(id),
  CONSTRAINT transfer_pricing_vehicle_type_id_fkey FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_types(id),
  CONSTRAINT transfer_pricing_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.transfer_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  event_id uuid,
  name character varying NOT NULL,
  code character varying,
  transfer_type character varying NOT NULL,
  direction character varying CHECK (direction::text = ANY (ARRAY['inbound'::character varying, 'outbound'::character varying, 'round_trip'::character varying, 'one_way'::character varying]::text[])),
  origin_type character varying,
  origin_name character varying,
  origin_address text,
  destination_type character varying,
  destination_name character varying,
  destination_address text,
  distance_km numeric,
  estimated_duration_minutes integer,
  operates_on_dates jsonb DEFAULT '[]'::jsonb,
  default_departure_time time without time zone,
  default_return_time time without time zone,
  pickup_instructions text,
  dropoff_instructions text,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT transfer_routes_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_routes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT transfer_routes_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.transfer_sales_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid NOT NULL,
  transfer_date date NOT NULL,
  departure_time time without time zone,
  vehicle_type_id uuid,
  seats_sold integer DEFAULT 0,
  vehicles_sold integer DEFAULT 0,
  estimated_vehicles_needed integer,
  actual_vehicles_allocated integer,
  supplier_id uuid,
  actual_cost numeric,
  currency character varying DEFAULT 'GBP'::character varying,
  supplier_confirmed boolean DEFAULT false,
  supplier_confirmation_date date,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transfer_sales_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT transfer_sales_tracking_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.transfer_routes(id),
  CONSTRAINT transfer_sales_tracking_vehicle_type_id_fkey FOREIGN KEY (vehicle_type_id) REFERENCES public.vehicle_types(id),
  CONSTRAINT transfer_sales_tracking_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT transfer_sales_tracking_currency_fkey FOREIGN KEY (currency) REFERENCES public.currencies(code)
);
CREATE TABLE public.vehicle_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  code character varying,
  capacity integer NOT NULL CHECK (capacity > 0),
  description text,
  amenities jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT vehicle_types_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_types_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.venues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  venue_type character varying,
  city character varying,
  country_code character varying,
  capacity integer,
  latitude numeric,
  longitude numeric,
  timezone character varying,
  description text,
  images jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp with time zone,
  CONSTRAINT venues_pkey PRIMARY KEY (id),
  CONSTRAINT venues_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT venues_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code)
);